// <auto-generated />
namespace Vidly_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedMembershipTypeEagerLoadingAndUpdateCustomerDetailsView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedMembershipTypeEagerLoadingAndUpdateCustomerDetailsView));
        
        string IMigrationMetadata.Id
        {
            get { return "201911091153048_AddedMembershipTypeEagerLoadingAndUpdateCustomerDetailsView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
